### ISSUE TITLE
How to start the game?!

### ISSUE THREAD

**Issue by bharatkrishna** [jdolan/quake2#13]
I downloaded the .dmg and instal quake 2 app. Then I put PAK0.PAK in ~/.quake2/baseq2. When I start the game from the app, I get the console. How do I start the game from here? 

This is my directory structure:

```
.quake2/
└── baseq2
    ├── PAK0.PAK
    ├── aprconfig.cfg
    └── save
        └── current
```

**Comment by bharatkrishna** [comment]
Okay, I managed to find out how to start the game. On the console I had to type `menu_game`.

**Comment by jdolan** [comment]
Hi, sorry. I was traveling this weekend. I'm surprised by this.. pressing ESC didn't bring up the menus?
