### ISSUE TITLE
Compilation fails on High Sierra (10.13)

### ISSUE THREAD

**Issue by eternalistic** [jdolan/quake2#16]
I just upgraded to High Sierra and my previously working version of Quake II was no longer playable and would hang once loaded and displaying the console.

So I downloaded a fresh copy of `master` hoping I could compile a new version and get that running.

I ran `make` and received this error:

```
[LD] quake2
Undefined symbols for architecture x86_64:
  "_inflateValidate", referenced from:
      _png_inflate_claim in libpng.a(pngrutil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/quake2] Error 1
make: *** [debug] Error 2
```

Any idea how to get it to compile correctly?

**Comment by jdolan** [comment]
Hm. Looks like you're statically linked against libpng there. How did you install libpng and libSDL? Macports? Have you tried rebuilding your ports or Homebrew since upgrading to High Sierra?

**Comment by jdolan** [comment]
I have not yet upgraded, or I'd try this for myself.. I need to wait until it's been confirmed that Pioneer Rekordbox works on High Sierra ;)

**Comment by eternalistic** [comment]
@jdolan, thanks for the direction. I was able to get `make` to build successfully and without error once I fixed a few issues with Homebrew. Just ran `brew doctor` and it showed me some files that were incorrectly linked and extra files that needed to be removed and could cause conflict.
