### ISSUE TITLE
Trying to finish installation, getting rsync error

### ISSUE THREAD

**Issue by frydj** [jdolan/quake2#21]
When running the command:

./data/install-data.py

I am getting error:

rsync: failed to connect to quake2world.net (129.121.33.21): Connection refused (61)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

Any suggestions?  It looks like quake2world.net isn't Quake 2 related anymore...

**Comment by jdolan** [comment]
Yea.. in theory, that would come from quetoo.org these days, but I actually do not run a public rsync server there anymore. That install path is no longer available, sorry. Honestly, you may be better off running a more maintained Quake2 port such as Yamagi or q2pro. The binaries from this port should still work, but there are known issues and I just don't have time to address them. This port is no longer maintained.

**Comment by frydj** [comment]
Too bad for me! Thanks for replying. 👍
