### ISSUE TITLE
Makefile deleting nearly all my Applications!!

### ISSUE THREAD

**Issue by DESER90** [jdolan/quake2#23]
I'm new to Github.

I've downloaded Quake 2. 
Don't ask me why, but the first thing I did was run the Makefile.
Terminal came up saying apps didn't get permission. I quit Terminal after 10 seconds, thinking it was weird.
Suddenly many Applications on my mac High Sierra 10.13.6 got removed!!
Not so happy right now. Please tell me how this is possible.

**Comment by jdolan** [comment]
lolwut?
