### ISSUE TITLE
Doesn't open on Big Sur (M1)

### ISSUE THREAD

**Issue by dhdanno** [jdolan/quake2#24]
Says package is damaged

**Comment by jar3817** [comment]
I run jdolan's Q2Pro build on my M1 Macbook, works great (1600+ fps): 
[https://q2.packetflinger.com/dl/q2pro/q2pro.dmg](https://q2.packetflinger.com/dl/q2pro/q2pro.dmg)

Just copy to application folder and run the python script to download all the required assets
