### ISSUE TITLE
Enabling CD audio

### ISSUE THREAD

**Issue by asublin** [jdolan/quake2#4]
There's no option for playing cd audio in my compiled version (last revision I presume). I see that in the code there is a CD_AUDIO conditional macro all over the code. But I don't know where to enable it. I suppose I need to add a `#define CD_AUDIO` in some file, but I don't know which. Or do I need to pass that in the make command line?

**Comment by jdolan** [comment]
Check the Makefile. You can try to enable it, but I'm pretty sure it didn't compile on OS X for me (I think SDL 1.2 does not have CD support on OS X).

**Comment by asublin** [comment]
I'm not sure how to enable it. I've added `-DCD_AUDIO` at the end of the line 20 for the `CFLAGS` definition. Recompiled but still not there in the options.

**Comment by jdolan** [comment]
Yea, if you look at `cd_linux.c` you can see that there are no code paths enabled for `__APPLE__`.

This post summarizes the issue pretty well:
https://discussions.apple.com/thread/1946430?start=0&tstart=0

Closing out, this can't be fixed without significant new development.

**Comment by asublin** [comment]
But I'm using linux, not os x. Anyway, I guess I'll bite the bullet try to get deep into the code to understand it.

**Comment by jdolan** [comment]
Oh! Hah. Well, in that case, adding `-DCD_AUDIO` to `CFLAGS` in `Makefile` should do it. I will actually enable that by default, as it doesn't do any harm to OS X compilation.
